= Neng Password Manager

A basic password manager written in Rust. Supports two modes of interacting with it: through the command line (`neng-pass` binary crate), or through a GUI (the `neng-pass-gui` crate), built with Tauri.

*DISCLAIMER: Because this is just a dumb personal project I made in my spare time, I cannot guarantee that it will be 100% secure. DO NOT ACTUALLY USE THIS FOR ANYTHING SERIOUS!!!*

== Where's the EXE???

As a wise man once said,

"I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it 
https://github.com/sherlock-project/sherlock#installation WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. 
these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. 
I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS"
-- https://old.reddit.com/r/github/comments/1at9br4/i_am_new_to_github_and_i_have_lots_to_say/[u/automatic_purpose_]

=== Here's the EXE

For some reasons, I have been kind enough to provide you, the non-programmers who happens to on GitHub for some reasons, the EXE file.

https://github.com/earthtraveller1/neng-pass/releases/download/1.0/neng-pass-gui.exe[neng-pass-gui.exe]

Please appreciate this grand act of kindness, as you will likely not see it from other developers on this cringe site.

Anyways, for those of you who are actually programmers, here's some instructions to build from source.

== Building from Source

Ensure that you have the following installed:

- https://www.rust-lang.org/tools/install[Rust]
- https://nodejs.org/en/download/[Node.js] (or any of the alternative JavaScript runtimes, like Deno, Bun, or whatever is out here these days).
- Dependencies of the Tauri framework for your specific operating system. Check this list https://tauri.app/v1/guides/getting-started/prerequisites/[here].

First, clone the repository:

[source,bash]
----
git clone https://github.com/earthtraveller1/neng-pass.git
----

From there, you can run the the CLI tool:

[source,bash]
----
cd neng-pass
cargo run --release
----

=== Building the GUI

First, you need to install the dependencies for the frontend. This is assuming that you are using NPM.

[source,bash]
----
cd neng-pass/neng-pass-gui
npm install
----

For the next step, you will need the Tauri CLI tool. If you have cargo installed, you can run:

[source,bash]
----
cargo install tauri-cli
----

After that's done, you can simply run:

[source,bash]
----
cargo tauri dev
----

To run the application. It will be in debug mode, so it might be a bit slow, but it should work.

== CLI Reference

Basic, quick reference for the CLI tool. I won't go into too much detail, you can utilize the help command to learn more about the options within each subcommand.

----
❯ target/release/neng-pass.exe --help
Basic password manager written in Rust (btw)

Usage: neng-pass <COMMAND>

Commands:
  set-master  Sets the master key
  new         Creates a new password with the specified name.
  save        Saves a new password with the specified name and value.
  get         Gets the value of a specific password.
  list        Gets a list of all the passwords that you have saved right now.
  delete      Deletes a specific password from your password list. Remember that this is not reversible!!!!
  help        Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
----
